---
title: Stoom
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Nerdlab
description: Wat als kunst en technologie samenkomen? Een vraag waar we bij Nerdlab
  vaak over nadenken, en waar we jou voor nodig hebben!
permalink: pretty
exclude:
- _site
- scss
- "*scss"
- Gem*
- Guard*
- "*rb"
- ".sass-cache"
- ".git*"
- config.rb
- "*.md"
- "*.json"
- docroot
- node_modules
- gulpfile.js
- install.sh
- lint.yml
